// <auto-generated />
namespace Anabeesh.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class extenduserprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extenduserprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "201801191316271_extend-user-profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
